trane-project/trane

Cargo.toml
src/practice_stats.rs

Size grows quickly if the raw IDs are stored in every row. Instead, have
a table of uids which store the IDs and have the other table reference
it when looking up scores.
Breaking change. DBs created in previous versions won't work.

Store uids instead of IDs in practice stats DB.

---

src/lib.rs
src/scheduler.rs
src/scheduler/cache.rs
src/scheduler/data.rs
src/scorer.rs
src/scorer/test.rs
tests/basic_tests.rs
tests/common.rs

- Non-blacklisted courses were accidentally receiving a None score.
- Changing name `ExerciseScheduler::record_exercise_score` because it was colliding with
`PracticeStats::record_exercise_score`, causing the score cache to not be updated.
- An exercise with no previous scores now has a score of 0.0 instead of None.
- Ignore a lesson's dependency on its course when deciding if all the dependencies are
satisfied.
- A metadata filter with course and lesson filters will return false for the course so that the
course is skipped and the decision is made when the lesson is reached. Otherwise, exercises
in the course that do not match the filter were being added.
- Added a regression test in basic_tests.

Fix multiple bugs

---

src/blacklist.rs
src/course_library.rs
src/graph.rs

There's no need to add these dependencies to the graph because the
scheduler already takes care of only adding the starting lessons
when a course is first encountered.

Remove implicit dependencies.

---

src/graph.rs
src/graph/tests.rs
src/lib.rs
src/scheduler.rs
src/scheduler/cache.rs
tests/basic_tests.rs
tests/large_tests.rs

Big performance improvement but have to invalidate all the scores when the blacklist is updated
or else the dependent lessons could be incorrectly scheduled/not scheduled.

Cache lesson scores

---

src/scheduler/cache.rs
tests/basic_tests.rs

An early return meant that some None values were not being cached.
This PR also improves the test that verifies that the lesson cache is
properly invalidated.

Fix early return in get_lesson_score

---

src/scheduler/filter.rs
tests/basic_tests.rs

Add the remainders to the batch in ascending order of difficulty (i.e.
mastered exercises are added first). This seems to reduce the number of
batches needed to schedule all the exercises.

Reduce number of batches needed to schedule all exercises

---

src/scheduler.rs
tests/basic_tests.rs

The starting lessons in the courses in the course filter should be added regardless of whether their dependencies are satisfied.

Fix bug in scheduler

---

src/scheduler.rs

The calculation was being done based on the scores before the blacklisted exercises were filtered out. Instead, it should be done based on the final list.

Fix bug calculating the average score of a lesson

---

src/scheduler.rs
tests/basic_tests.rs

There cannot be missing dependents because a unit only declares its dependencies. This makes it impossible to have missing units after the missing starting units are removed before being added to the initial stack.
This PR removes the logic to check for missing units and adds more missing dependencies to the tests to make sure the scheduler works with missing dependencies.

Remove missing unit checks in scheduler

---

src/graph.rs
src/scheduler.rs
tests/large_tests.rs

The course was being ignored and the entire graph was not being traversed as a result. Instead, add such courses to the initial stack so that its dependents can be traversed.
Also, remove lessons with existing courses from the dependency sinks.

Fix bugs when a starting course has no lessons

---

src/scorer.rs

Give more weight to recent scores and reduce the amount each score is adjusted based on the days since the trial.

Adjust scoring factors

---

Cargo.toml
src/practice_stats.rs

Does not look like databases created in earlier versions can be opened if these migrations are removed.

Restore migrations from earlier versions.

---

src/data.rs
src/scheduler/cache.rs
src/scorer.rs

- Set the default number of trials used to compute the score to 20.
- Set the default passing score to 3.75 and adjust the scoring windows accordingly.
- Set the factor by which scores are reduced with each passing day to 0.01.

Adjust scoring options:

---

src/data.rs

Initially all manifests had the same name so they could be confused when reading the library. This is no longer the case, so the directive can be removed.

Remove deny_unknown_fields directive

---

src/data.rs
src/data/course_generator/music_piece.rs
src/lib.rs
src/testutil.rs
tests/knowledge_base_tests.rs

The working directory from which to resolve relative paths needs to be manually set by the caller.

Fix issues with working directory.

---

Cargo.toml
src/course_builder/knowledge_base_builder.rs
src/data.rs
src/data/course_generator/knowledge_base.rs
src/testutil.rs
tests/knowledge_base_tests.rs

Some exercises do not really need a back, as they merely reference an external resource, for example.

Allow flashcard assets to have no back.

---

src/course_library.rs
src/scheduler.rs

Newer versions of tantivy require more memory during the indexing phase. Otherwise the indexing phase will be a lot slower than in previous versions.
See https://github.com/quickwit-oss/tantivy/issues/2156 for details.

Improve performance due to slow indexing

---

src/scheduler.rs
tests/superseded_tests.rs

If unit A is superseded by unit B and unit B is in turn superseded by unit C, then unit A should be considered to be superseded by unit C when unit B is superseded by unit C.

Superseded units should work recursively

---

src/scheduler.rs
src/scheduler/cache.rs
tests/superseded_tests.rs

Superseded units that have low scores themselves were blocking progress.

Fix bugs when scheduling superseded units

---

Cargo.toml
src/blacklist.rs
src/ffi.rs
src/lib.rs
src/practice_stats.rs
src/review_list.rs
src/scheduler.rs
src/scheduler/cache.rs
src/scheduler/data.rs
src/testutil.rs
tests/knowledge_base_tests.rs

Call them LocalBlacklist, etc., in contrast to possible remote implementations.
Use dynamic dispatch in SchedulerData instead of implementations. No significant performance degradation observed in actual testing.

Consistent naming of local trait implementations

---

ffi/trane.ts
src/data.rs
src/data/course_generator/transcription.rs
src/data/ffi.rs

The raw external link needs to be associated with each exercise to more easily download the audio for the exercise.

Modify transcription exercises to include external link

---

src/course_builder/knowledge_base_builder.rs
src/data.rs
src/data/course_generator/transcription.rs

Keep serialization of those that are important and will more likely need to be filled.

Skip serialization of most default fields

---

src/data.rs

The superseding unit should have a high score for the other unit to be replaced. 3.75 is not high enough.

Increase superseding score to 4
