trane-project/trane

src/graph.rs
src/scheduler.rs
tests/basic_tests.rs

A branch which starts with a missing course should still be traversed by
using their dependents instead.

Handle missing starting courses properly.

---

src/course_library.rs
src/lib.rs
src/scheduler.rs
src/scheduler/cache.rs

There's no multithreading at all yet so there's no point in having
Arc's instead of Rc's. Plus rusqlite connections are not thread-safe.

Replace Arc<RwLock<_>> with Rc<RefCell<_>>

---

Cargo.toml
src/graph.rs
src/graph/tests.rs
src/lib.rs

Useful to visualize the graph using graphviz

Generate DOT graph from the unit graph.

---

src/course_library.rs

Currently, the logic opens the files whose full path has a matching
suffix. It now opens only those files whose file name is exactly the
expected value.

Only open manifests with the expected file name.

---

README.md

- Add more modules to code tour.
- Reorder badges.

More work on README

---

src/course_library.rs
src/graph.rs
src/lib.rs
src/practice_stats.rs
src/scheduler.rs

Also fix a couple of wording issues in graph.rs

Add links to other crates in documentation

---

src/blacklist.rs
src/course_builder.rs
src/course_library.rs
src/data.rs
src/data/filter.rs
src/filter_manager.rs
src/graph.rs
src/lib.rs
src/practice_stats.rs
src/review_list.rs
src/scheduler.rs
src/scheduler/cache.rs
src/scheduler/data.rs
src/scheduler/filter.rs
src/scorer.rs

Some minor refactoring as well

More documentation and comments

---

src/scorer.rs

Previously, if an user tries a new exercise multiple times in the first few
days, the weights of their scores will be the same. This will make it
hard to get a passing score if the user makes fast progress.
This change adds a step to adjust the weight of the scores based on the index
of the trial in the list.

Give more weight to more recent scores.

---

src/scheduler/cache.rs
src/scorer.rs

Also modify the interface so that the scores are borrowed.

Reduce the score adjustment factor from 0.1 to 0.05

---

src/data/course_generator/improvisation.rs
src/data/course_generator/improvisation/constants.rs
src/data/course_generator/music_piece.rs

Also rephrase the instructions for the improvisation course to make it clear which exercises are meant to be done in a specific key.

Add singing instructions to music piece course

---

src/data/course_generator/music_piece.rs
tests/music_piece_tests.rs

Makes the JSON serialization easier to write.

Make MusicPassage a struct and not an enum

---

src/scorer.rs

The scores should decrease faster during the first few days, then decrease slower.

Improve scores adjustment

---

src/scheduler/filter.rs

Weight due to the frequency of the exercise should be halved. Readjust the other portions of the final weight accordingly.

Improve how weight of exercises to filter is calculated

---

src/scheduler/filter.rs

Also ensure at least one candidate from each bucket is selected.

Improve how remainders are added into the batch

---

src/data.rs

Range should go from 4.5 to 5.0

Change mastery window ranges

---

src/scheduler/filter.rs

Adjust the batch size to a smaller size if there are not enough candidates. This prevents situations in which the batches contains most of the exercises available to the student.

Dynamic batch size

---

src/data/filter.rs
src/filter_manager.rs
src/lib.rs
src/scheduler.rs
src/scheduler/data.rs
src/testutil.rs
tests/basic_tests.rs

A student is able to tell trane what part of the graph they want to schedule and for how long. For example, a student could practice piano for an hour and ear traning for the next 30 minutes.

Add study session feature

---

src/course_library.rs
src/data/filter.rs
src/lib.rs
src/scheduler/data.rs
src/study_session_manager.rs
tests/basic_tests.rs

Let trane save and reuse study sessions.

Add study session manager

---

src/data/course_generator/transcription.rs
tests/transcription_tests.rs

Transcription lessons should depend on the transcription lesson from the courses listed as a dependency.

Improve dependencies in transcription courses

---

src/course_library.rs
src/error.rs
src/lib.rs
tests/basic_tests.rs
tests/improvisation_tests.rs
tests/knowledge_base_tests.rs
tests/music_piece_tests.rs
tests/transcription_tests.rs

Simplify the return values returned by the methods in the trait as well.

Improve errors for course_library module

---

src/error.rs
src/graph.rs
src/lib.rs
src/practice_stats.rs
src/repository_manager.rs

Also remove generic errors since anyhow works better for those.

Improve errors for graph module

---

Cargo.toml
ffi/trane.kt
ffi/trane.swift
ffi/trane.ts
src/data.rs
src/data/ffi.rs
src/data/ffi/filter.rs
src/data/filter.rs
src/ffi.rs
src/lib.rs
src/scheduler.rs
src/testutil.rs
tests/basic_tests.rs

Add TraneFFI type for easier interop and finish converting all required types to their FFI versions.

Finish FFI implementation

---

ffi/trane.kt
ffi/trane.swift
ffi/trane.ts
src/data/course_generator/transcription.rs
src/data/ffi/course_generator.rs
tests/transcription_tests.rs

Useful when dealing with backing tracks that do not have too many melodies or are otherwise low in information.

Add option to skip singing lessons

---

src/course_library.rs
src/ffi.rs
src/lib.rs
tests/basic_tests.rs
tests/knowledge_base_tests.rs
tests/music_piece_tests.rs
tests/transcription_tests.rs

Allow to retrieve the exercises from any unit or the whole library.

Improve method to retrieve exercises

---

src/scheduler.rs
src/scheduler/cache.rs
src/scheduler/data.rs
tests/superseded_tests.rs
tests/transcription_tests.rs

Only mark a unit as superseded if all its valid exercises have a valid score.

Improve superseded semantics

---

src/scheduler/filter.rs

Adjust the factors so the maximum weight for each of this factors is
200. The total maximum weight for a candidate is now 1000.

Adjust the maximum weight based on score, depth, and lesson frequency

---

src/data/course_generator/knowledge_base.rs
src/data/course_generator/transcription.rs
src/data/filter.rs
src/graph.rs
src/lib.rs
src/scheduler.rs
src/scheduler/filter.rs
tests/blacklist_tests.rs

Includes fixes to new lints in rust 1.73.

Fix code coverage

---

CONTRIBUTING.md

Well, I know you're not accepting pull requests but this one should slide right in!

Fix spelling issue in CONTRIBUTING.md

---

bindings/CourseManifest.ts
bindings/LessonManifest.ts
bindings/SchedulerOptions.ts
src/data.rs
src/lib.rs
src/practice_rewards.rs
src/rewarder.rs
src/scheduler.rs
src/scheduler/data.rs
src/scheduler/unit_scorer.rs

Basic outline of the implementation with no effect on scores for now.

Reward skeleton

---

src/blacklist.rs
src/db_utils.rs
src/practice_rewards.rs
src/practice_stats.rs
src/review_list.rs
src/scheduler/unit_scorer.rs

Adding the reward system requires that invalidating the score of a lesson or course invalidates the score of all units within it.

Fix cache invalidation

---

src/scheduler/filter.rs

The number of candidates to add from the remainders is now a fraction of the batch size. Also, add some exercises from the remainder of the mastered exercises.

Improve filtering

---

src/scheduler/filter.rs

Start with adding the current window's remainder. Otherwise the batches might have too many new exercises and not enough review.

More tuning of filtering logic
